services:
  - type: web             # Ab yeh Web Service ban gaya hai
    name: axiom-extractor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free            # Render Free Plan
    envVars:
      - key: BOT_TOKEN
        sync: false       
      - key: TRIGGER_CMD
        value: .liketect
